@ECHO OFF
REM CALL python ..\runner.py "diagnose" "me"
REM CALL python ..\runner.py "run_notebook" "notebook"
REM CALL python ..\runner.py "open_notebook" "this notebook"
REM CALL python ..\runner.py "search_notebook" "SOP"
REM CALL python ..\runner.py "list_notebook" 
REM CALL python ..\runner.py "history" 
REM CALL python ..\runner.py "next_notebook" 
REM CALL python ..\runner.py "new_scene" "me"
REM CALL python ..\runner.py "end_scene" 
REM CALL python ..\runner.py "change_scene" 
REM CALL python ..\runner.py "resume_scene" 
 CALL python ..\runner.py "delete_scene" "me"
REM CALL python ..\runner.py "list_scene" 
REM CALL python ..\runner.py "add_library" 
REM CALL python ..\runner.py "set_env" "me"
REM CALL python ..\runner.py "delete_env" 
